# This is a config for E2B sandbox template.
# You can use template ID (8j4v32nu1uebpvrfnel9) or template name (cuddlecraft-nextjs-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("cuddlecraft-nextjs-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("cuddlecraft-nextjs-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('cuddlecraft-nextjs-test-2')

team_id = "c33b69e0-4cb2-43e0-9794-e93aed1e5328"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "cuddlecraft-nextjs-test-2"
template_id = "8j4v32nu1uebpvrfnel9"
